### ISSUE TITLE
클린코드 & 시큐어코딩 클릭시 404 Not Found가 발생합니다.

### ISSUE THREAD

**Issue by ksundong** [kim6394/Dev_BasicKnowledge#22]
![image](https://user-images.githubusercontent.com/38597469/66185818-8b309300-e6bb-11e9-975b-df53a2b297d2.png)
![image](https://user-images.githubusercontent.com/38597469/66185844-a4394400-e6bb-11e9-98d2-5da7fdebb609.png)

https://github.com/kim6394/Dev_BasicKnowledge/blob/master/Concept/%ED%81%B4%EB%A6%B0%EC%BD%94%EB%93%9C(Clean%20Code)%20%26%20%EC%8B%9C%ED%81%90%EC%96%B4%EC%BD%94%EB%94%A9(Secure%20Coding)%20-%20%EB%B3%B5%EC%82%AC%EB%B3%B8.md
이 알맞은 경로인 것 같습니다.

**Comment by kim6394** [comment]
ksundong님 감사드립니다. README 수정 완료했습니다😊
